### ISSUE TITLE
Deploy process is broken on production server

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure-tools#10]
It appears a few things are goofing when `npm` installs current revisions of packages, which then are complaining that Ruby 2.x is needed.  Forcing the build manually had a lot of errors so I just build it locally for this deploy.

**Comment by brucecrevensten** [comment]
This seems to be working, but the output seems to contain a number of errors, which is disconcerting.  Could you try this out, note the errors produced and see if you can determine the cause?

**Comment by BobTorgerson** [comment]
One of the errors was an easy one to resolve. I never moved out of the CWD before deleting the mapventure repository. That leaves the CWD as the deleted directory, which Unix does not like. I've modified that process and now it doesn't have the final error of this script.

However, I'm having a bit of trouble figuring out the other warnings / errors as Grunt appears to not build the CSS files out of the Sass files on the first run through of the build process. However, after the build doesn't succeed the first time, the build does successfully find the files in question. Here is the error below: 

> Running "compass:dist" (compass) task
>     directory .tmp/styles
>         error app/styles/main.scss (Line 2: File to import not found or unreadable: plugins.
>     Load paths:
>       /tmp/mapventure/bower_components
>       Compass::SpriteImporter
>       /tmp/mapventure/app/styles
>       /var/lib/gems/1.9.1/gems/compass-core-1.0.3/stylesheets)
>         write .tmp/styles/map.css (0.027s)
>     Compilation failed in 1 files.
>     Warning: ↑ Used --force, continuing.
>     Done, but with warnings.

**Comment by brucecrevensten** [comment]
Production deploy worked last time, closing this!
